name: Build Binary Ritchie When PR Opens
on: [pull_request]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Create binary from branch
        run: cp "$GITHUB_EVENT_PATH" "$GITHUB_WORKSPACE/event.json"

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: event-json
          path: ./event.json

      - name: Cat GIT HUB EVENT
        run: cat $GITHUB_EVENT_PATH