name: Build Binary Ritchie When PR Opens
on: [pull_request]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Create binary from branch
        run: |
          echo GITHUB_EVENT_PATH
          echo "$GITHUB_EVENT_PATH"
          echo "--------------------"
          cd $GITHUB_WORKSPACE
          touch teste.txt

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: rit-linux
          path: ./test.txt

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: GITHUB_EVENT_PATH
          path: "${{ GITHUB_EVENT_PATH }}"

      - name: Pull Request Number
        id: pull-request-number
        run: echo "::set-output name=pull-request-number::$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")"

      - name: Cat GIT HUB EVENT
        run: cat $GITHUB_EVENT_PATH