name: List Artifacts and Update Pull Request Body
on:
  workflow_run:
    workflows: ["Build Binary Ritchie When PR Opens"]
    types: [completed]

jobs:
  list-artifacts-edit-pr-body:
    runs-on: ubuntu-latest
    steps:
      - name: Download workflow artifact
        uses: dawidd6/action-download-artifact@v2.11.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build-binary-when-pr-open.yml
          run_id: ${{ github.event.workflow_run.id }}

      - name: Pull Request Number
        id: pull-request-number
        run: |
          echo "::set-output name=pr-number::$(jq --raw-output .pull_request.number ./event-json/event.json)"
          echo "::steps.pull-request-number.outputs.pr-number": ${{ steps.pull-request-number.outputs.pr-number }}

      - name: List artifacts
        id: list-artifacts
        uses: chiaretto/github-action-list-artifacts-pr@master
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Update PR Body
        uses: chiaretto/github-action-concat-pr-body@master
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          message: "
        ### This pull request generated the following artifacts.

  To test the health and quality of this implementation, download the respective binary
  for your operating system, unzip and directly run the binary like the examples below.

  - **Linux**\r
  Download the file: **[rit-linux.zip](${{ steps.list-artifacts.outputs.rit-linux}})**\r
  URL: ${{ steps.list-artifacts.outputs.rit-linux}}\r
  Unzip to some folder like: `/home/user/downloads/pr${{ steps.pull-request-number.outputs.pull-request-number }}`\r
  Access the folder: `cd /home/user/downloads/pr${{ steps.pull-request-number.outputs.pull-request-number }}`\r
  Assign execute permission to binary: `chmod +x ./rit`\r
  Directly call the binary: `./rit --version` or `./rit.exe name of formula`\r
  \r\r"
          replace-last-message: true
          pr-number: ${{ steps.pull-request-number.outputs.pr-number }}